services:
  mc:
    image: itzg/minecraft-server:java17
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "24454:24454"
    environment:
      EULA: "TRUE"
      TYPE: "AUTO_CURSEFORGE"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/homestead-cozy"
      CF_API_KEY: ${CF_API_KEY}
      MEMORY: "8192M"
      MOTD: "Homestead - Time to get cosy."
      ENABLE_COMMAND_BLOCK: "true"
      SIMULATION_DISTANCE: "8"
      VIEW_DISTANCE: "8"
      SEED: "butts"
      LEVEL: "hs_catbug"
      OPS: |-
        UncleCeiling
        proXfizzy
      ALLOW_FLIGHT: "true"
    volumes:
      - "./data:/data"
    restart: always
